### ISSUE TITLE
Difficulty installing jpype for IDTxl, jpype1-py31 not working

### ISSUE THREAD

**Issue by jpainam** [pwollstadt/IDTxl#25]
Hi, I installed all the requirement and failed to install jpype properly. I used this [issue ](https://github.com/jpype-project/jpype/issues/390)to solve the installation of jpype. `pip install JPype1-py3`
Now, when testing this [code ](https://github.com/pwollstadt/IDTxl/wiki). I get this error
```python
\lib\site-packages\jpype\_jpackage.py", line 53, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package infodynamics.measures.continuous.gaussian.ConditionalMutualInfoCalculatorMultiVariateGauss
ian is not Callable
```
Following the installation, it seems that i installed the wrong version of jpype. I uninstalle `jpype1-py3` and try to install `jpype1` but failed with this error
```python
Temp\pip-install-id1phcwx\jpype1\setup.py:173: FeatureNotice: Turned ON Numpy
 support for fast Java array access
      FeatureNotice)
    building '_jpype' extension
    error: Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": www.microsoft.com/
download/details.aspx?id=8279
```
Thank for pointing to the right solution.
:)

**Comment by jlizier** [comment]
Hi Jean-Paul,
I think the answer lies directly in the error message you posted: you need to install MS Visual C++ so that the installation process for jpype1 can build the library. This is not a requirement for Jpype on Ubuntu (preferred idtxl platform), but is on windows which I assume you are using. More details on Jpype requirements on windows are available at https://jpype.readthedocs.io/en/latest/install.html#windows
Could you install what is pointed to from that page and confirm pls? If that works, Patricia perhaps you could add a brief note on that requirement on the [installation wiki page](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements)
--joe

**Comment by jpainam** [comment]
Hi. I followed the jpype install but this didn't solve the problem. But I managed to get Microsoft Windows SDK 7.1 [here](http://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=4422). I followed this [answers](https://www.mathworks.com/matlabcentral/answers/96611-how-do-i-install-microsoft-visual-c-2010-and-microsoft-windows-sdk-7-1). I must it is not an easy task to install these requirements. Patricia can update the documentation to point windows users to Microsoft Build Tools as requirements.
Now I have another error and will try to open an issue in jpype repo

```python
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\Include\intrin.h(26) : fatal error C1083: Cannot ope n include file: 'ammintrin.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\x86_amd64\\cl.exe' failed w ith exit status 2
```
