### ISSUE TITLE
how to conduct TTEST2 between two groups

### ISSUE THREAD

**Issue by jpainam** [pwollstadt/IDTxl#28]
Hi,
I'm using IDTxl to do my experiments, and I would like to get the `TTEST2` of two groups.
Is it possible to have it done using this tool?
In MATLAB, I'm able to run the `ttests2` for the two groups. 
Any help will be appreciated
Thank you.

**Comment by mwibral** [comment]
Dear Jean-Paul,

 

since TE values are not guaranteed to be normally distributed, we strongly favor non-parametric permutation testing. There are the corresponding options for comparing groups in IDTxl using permutation testing.

 

Best,

Michael

 

Gesendet: Montag, 21. Januar 2019 um 15:20 Uhr
Von: "Jean-Paul AINAM" <notifications@github.com>
An: pwollstadt/IDTxl <IDTxl@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [pwollstadt/IDTxl] how to conduct TTEST2 between two groups (#28)


Hi,
I'm using IDTxl to do my experiments, and I would like to get the TTEST2 of two groups.
Is it possible to have it done using this tool?
In MATLAB, I'm able to run the ttests2 for the two groups.
Any help will be appreciated
Thank you.

**Comment by pwollstadt** [comment]
@jpainam I will close this issue since there seems to be no problem with the code (if there is, please reopen this issue or raise a new one). We try to only handle bug reports via Github's issue tracker. For questions and discussions please post to [IDTxl's google groups](https://groups.google.com/forum/#!forum/idtxl) or write me an email.
