### ISSUE TITLE
How to use this package in pycharm (win7)? Thank you.

### ISSUE THREAD

**Issue by GoForit-007** [pwollstadt/IDTxl#47]
Hello,
I want to use this tool in windows system. However, I don't know how to use it. Could you provide the corresponding usage? Thanks a lot

**Comment by pwollstadt** [comment]
Hi @GoForit-007, in general we don't offer windows support. However, I didn't have any problems when installing IDTxl under windows using anaconda (see the [conda installation instructions](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements#anaconda-installation) in the Wiki). To use the Honda environment (with IDTxl installed), see [how to use PyCharm with anaconda](https://docs.anaconda.com/anaconda/user-guide/tasks/pycharm/). Hope this helps. I will close this issue since it is not related to a bug in IDTxl's code. If you have more questions regarding usage, consider checking out the [IDTxl google group](https://groups.google.com/forum/#!forum/idtxl). Thanks!
